Add more JSDoc annotations + validate them and refactor to make them clearer
standard/standard-engine pull request #248
Opened 2021-08-14 18:18 UTC by voxpelli

**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[ ] Bug fix
[ ] New feature
[x] Other, please explain: To make #234 simpler to solve

**What changes did you make? (Give an overview)**

The main changes:

1. I extended the JSDoc types + added a validation of them using the TypeScript cli utility – this to better ensure that the public API contract doesn't get broken when I, @Divlo or someone else new to the code contributes.
2. In the process of adding the types I found that `parseOpts()` was a bit all over the place and unlike its name was actually mainly focused on simply constructing the needed ESLint Config. I therefore revamped it to be fully focused on that + extracted it into a file of its own to make both it and the main file shorter and more focused.
3. As a result of the revamping of `parseOpts()` and adding types, the custom `parseOpts` argument added in #146 also had to get a modification to it (or be removed – I searched through the entirety of GitHub and there's no public usage there of it at least). I replaced it with a new `resolveEslintConfig` argument which mimics the original one.

**Is there anything you'd like reviewers to focus on?**

- [ ] Whether the general approach is good and where we want to take this
- [ ] Actually test this with `standard` itself

**Why is this a draft PR?**

I haven't actually pulled in this version into `standard` itself and tried it there yet, wanted to get this up for some more eyes first, as eg. @Divlo has been working in this area as well.

2021-08-14 18:21 UTC, voxpelli commented
With these types it would also be possible to generate `.d.ts` files from this code, if we would like to publish with types.

Also – I failed to mention – the type strictness is pretty much to the max right now, because that's how I like it so that was what I aimed for. If others finds that annoyingly strict, then we can absolutely relax them – now or later.

2021-08-14 20:30 UTC, Divlo requested changes
> Whether the general approach is good and where we want to take this

I also like to add types to my JavaScript, I don't write JavaScript anymore for my personal project, whenever I can, I use TypeScript.
With this PR, we are nearly like using TypeScript and in fact, we are installing it to check the JSDoc types.

I would argue that we should choose the right tool for the right job, so if we want to add more types, it's probably better to transition the entire project to TypeScript, that would make more sense in my opinion.

I would be 100% agree to do this, but that would be a major change for the project, and it is more a decision to take from the creator of this original codebase: @feross, @Flet, @LinusU.

> Actually test this with standard itself

Yes, we should definitely test that `standard/standard don't break with this major change. :+1: 

> I searched through the entirety of GitHub and there's no public usage there of it at least

That still means, it is a *BREAKING CHANGE**, even if no one is actually using it.

---

Even if I don't agree with the current implementation (as the implementation should use TypeScript in my opinion), thank you for taking this PR, it will definitely make #234 simpler to solve, and the main idea behind this PR is a great idea. :smile:

2021-08-14 20:30 UTC, Divlo commented on lib/resolve-eslint-config.js
> +  // FIXME: This can be either string or string[]?
We should not leave `FIXME` comments in the codebase, so that should be fixed in this PR.

I think that `eslintConfig.ignorePattern` could be `string` or `string[]`, but I'm not sure at all, to verify.

2021-08-14 20:30 UTC, Divlo commented on lib/resolve-eslint-config.js
> +    // envs can be an object in `package.json`
Why there is this comment there?

2021-08-14 20:30 UTC, Divlo commented on lib/resolve-eslint-config.js
> +    // TODO: Document
By `TODO: Document`, do you mean to document in `README.md` ?
Is this new options that this PR adds ?

2021-08-14 20:30 UTC, Divlo commented on tsconfig.json
> +    "noUnusedParameters": true,
I don't think we need these options.
We could use `"strict": true` instead, it is better and stricter.

2021-08-14 20:30 UTC, Divlo commented on tsconfig.json
> +  "extends": "@tsconfig/node10/tsconfig.json",
We don't need to use the `tsconfig.json` from someone else, and the fewer configurations, the better it is.

In fact we don't need too much configurations for `tsconfig.json`, what are the settings you need from `@tsconfig/node10/tsconfig.json`?

I also don't like to specify the Node version in there.
We better define `tsconfig.json` ourselves.

2021-08-14 20:30 UTC, Divlo commented on index.js
> +      cmd: this.cmd
Is the order important there ?
I know it's a little thing not that much important, but just asking for clarification and to better understand what's going on. :smile:

We could do:
```js
{
  cwd: this.cwd,
  cmd: this.cmd,
  ...opts
}
```

Why? I know that should be only a stylistic thing, but at least it is easier to read, that first we are defining `cwd` and `cmd` and then we pass the rest of the options.

2021-08-14 21:15 UTC, voxpelli commented on bin/cmd.js
> +    if (!result) throw new Error('expected a result')
This shouldn't ever happen, but as `result` is allowed to be empty (because it is when `err` is set) we need to check it for the types to be inferred correctly.

If one does full-on typescript, then one can do function overloading and stuff.

If/when we move to promises, this weirdness goes away.

2021-08-14 21:16 UTC, voxpelli commented on bin/cmd.js
> +   * @type {(message?: any, ...optionalParams: any[]) => void}
True, this is actually the exact types that `console.log`/`console.error` has though, so I just copied them straight over.

Now that I think of it, I guess we would do this to make that clear:

```suggestion
   * @type {typeof console.log}
```

2021-08-14 21:16 UTC, voxpelli commented on lib/resolve-eslint-config.js
> +  // FIXME: This can be either string or string[]?
Oh, this one slipped through by mistake, good catch!

2021-08-14 21:17 UTC, voxpelli commented on lib/resolve-eslint-config.js
> +    // envs can be an object in `package.json`
It was there in the old script

2021-08-14 21:19 UTC, voxpelli commented on lib/resolve-eslint-config.js
> +    // TODO: Document
This refereed to the JSDoc types, I just forgot to remove it, was a bit sloppy apparently when I wrapped this up 😝

2021-08-14 21:24 UTC, voxpelli commented on tsconfig.json
> +  "extends": "@tsconfig/node10/tsconfig.json",
This is to ensure that the correct `lib` is set, which for Node 10 is [`es2018`](https://github.com/tsconfig/bases/blob/9391a13bc678ef6bf38e93071aa344511e62e2a5/bases/node10.json#L6), for Node 12 is [`["es2019", "es2020.promise", "es2020.bigint", "es2020.string"]`](https://github.com/tsconfig/bases/blob/9391a13bc678ef6bf38e93071aa344511e62e2a5/bases/node12.json#L6)

I personally find it to be clearer to extend it like this than to remember to set it all up oneself.

In a way, its the `standard` of `tsconfig` files 🙂

2021-08-14 21:27 UTC, voxpelli commented on tsconfig.json
> +    "noUnusedParameters": true,
`"strict": true` is [already set](https://github.com/tsconfig/bases/blob/9391a13bc678ef6bf38e93071aa344511e62e2a5/bases/node10.json#L10) in `@tsconfig/node10`, though these are not included there and has to be added manually, see [`noUncheckedIndexedAccess`](https://www.typescriptlang.org/tsconfig#noUncheckedIndexedAccess), [`noUnusedLocals`](https://www.typescriptlang.org/tsconfig#noUnusedLocals) and [`noUnusedParameters`](https://www.typescriptlang.org/tsconfig#noUnusedParameters) 🙂

2021-08-14 21:29 UTC, voxpelli commented on index.js
> +      cmd: this.cmd
`opts` is intended to be able to override `cwd` but not `cmd`, so yeah, the ordering matters 🙂

2021-08-14 21:34 UTC, voxpelli commented on lib/resolve-eslint-config.js
> +    // envs can be an object in `package.json`
Here: https://github.com/standard/standard-engine/blob/eb01fba0a880870b3c512323bf5ffa153c136bbb/index.js#L235-L238

2021-08-14 21:38 UTC, Divlo commented on tsconfig.json
> +    "noUnusedParameters": true,
Oh ok, great, we can keep these  settings then.

Didn't know, we could make TypeScript stricter than `"strict": true`.

2021-08-14 21:52 UTC, voxpelli commented
> > Whether the general approach is good and where we want to take this
> 
> I also like to add types to my JavaScript, I don't write JavaScript anymore for my personal project, whenever I can, I use TypeScript.
> With this PR, we are nearly like using TypeScript and in fact, we are installing it to check the JSDoc types.
> 
> I would argue that we should choose the right tool for the right job, so if we want to add more types, it's probably better to transition the entire project to TypeScript, that would make more sense in my opinion.
> 
> I would be 100% agree to do this, but that would be a major change for the project, and it is more a decision to take from the creator of this original codebase: @feross, @Flet, @LinusU.

We actually had JSDoc types before, but they were not validated and was hence quite incomplete. So basically what I mostly did was to add validation of those JSDoc comments, to help me complete them and to help us from avoiding regressions in them.

On TypeScript – it essentially consists of three parts – the validator, the type compiler and the code compiler – and one can use the validator and type compiler on JS code just as well as one can on TS code, but of course the code compiler is of no use for JS code as JS is already JS.

For a project of this size and complexity I would say that adding in a transpiler of any kind, TypeScript or otherwise, would be quite overkill and add nothing extra than what a JSDoc annotated JS gives 🙂 Except for a hard dependency on a transpiler step.

> > I searched through the entirety of GitHub and there's no public usage there of it at least
> 
> That still means, it is a **BREAKING CHANGE**, even if no one is actually using it.

Good point, I very much meant to write **BREAKING CHANGE**, it indeed is and since this is intended to target `15.x` it feels ok.

I'm do am wondering though whether it makes most sense to migrate the API to a new one or whether just dropping it would be better, when we know of no current use cases.

2021-08-14 21:55 UTC, voxpelli commented on tsconfig.json
> +    "noUnusedParameters": true,
In my own projects I'm [even crazier](https://github.com/voxpelli/tsconfig/blob/f1c6de23bace79b0173e1b734ce0a64523d92440/base.json#L22) and adds [`noPropertyAccessFromIndexSignature`](https://www.typescriptlang.org/tsconfig#noPropertyAccessFromIndexSignature) as well, but that felt like going a bit too far here

2021-08-15 21:42 UTC, Divlo commented on tsconfig.json
> +  "extends": "@tsconfig/node10/tsconfig.json",
Yes, that's mostly important if you are using TypeScript like Babel would do (convert modern features to old syntax, so it is supported).

But there is something easier (and in my opinion cleaner), here is how I would write this `tsconfig.json` file :
```json
{
  "files": [
    "index.js",
  ],
  "include": [
    "bin/**/*.js",
    "lib/**/*.js",
  ],
  "compilerOptions": {
    "target": "ESNext",
    "lib": ["ESNext"],
    "module": "commonjs",
    "moduleResolution": "node",
    "esModuleInterop": true,
    "strict": true,
    
    /* Configures it for targeting javascript */
    "allowJs": true,
    "checkJs": true,
    "noEmit": true,

    /* Adds additional checks beyond "strict": true  */
    "noUncheckedIndexedAccess": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
  }
}
```

Honestly, I think both are fine, so I make this conversation resolved, but I would rather not include @tsconfig/node10/tsconfig.json as dependencies, it is up to you. :smile:

2021-08-15 22:00 UTC, Divlo approved these changes
Overall, it Looks Good To Me. :+1:
But I would rather have a second review approval before merging this.
Also as you said, we should test this with `standard` itself.

> We actually had JSDoc types before, but they were not validated and was hence quite incomplete. So basically what I mostly did was to add validation of those JSDoc comments, to help me complete them and to help us from avoiding regressions in them.

You actually changed my mind. :smile: 
You are not wrong there, we were already using JSDoc comments, so why not add some extra checks for the CI to avoid regressions in the future. :+1:
But I still think a better implementation would be to migrate the project completely to TypeScript.

> For a project of this size and complexity I would say that adding in a transpiler of any kind, TypeScript or otherwise, would be quite overkill and add nothing extra than what a JSDoc annotated JS gives slightly_smiling_face Except for a hard dependency on a transpiler step.

The real ask there is: when is the size of the project sufficient, to use TypeScript ?
If the project becomes bigger and bigger, it will be even harder to migrate the project to TypeScript, right?
So I would say, it is not right in my opinion and TypeScript is the right tool no matter the size of the project.

The main advantages to use TypeScipt is the better syntax to do the same thing :

1.
```js
/** type {string[]} */
const result = []
```
vs
```ts
const result: string[] = []
```

2.
```js
/**
 * @typedef StandardCliOptions
 * @property {import('../').linter} [linter]
 * @property {string} [cmd]
 * @property {string} [tagline]
 * @property {string} [homepage]
 * @property {string} [bugs]
 */
```
vs
```ts
import type { linter as Linter } from '../'

interface StandardCliOptions {
  linter: Linter
  cmd: string
  tagline: string
  homepage: string
  bugs: string
}
```

2021-08-16 13:26 UTC, LinusU commented on README.md
>  ## API Usage
```suggestion
Modify and return `eslintConfig`, or return a new object with the eslint config to be used.

## API Usage
```

All other headers in this document has a blank line above it, which I personally also think is nice ☺️

2021-08-16 13:28 UTC, LinusU commented on bin/cmd.js
> +    if (!result) throw new Error('expected a result')
> If/when we move to promises, this weirdness goes away.

👍

2021-08-16 13:39 UTC, LinusU approved these changes
Looks good 👍 

Is this intended to go out as a major change, sine `parseOpts` was changed to `resolveEslintConfig`?

2021-08-16 13:56 UTC, voxpelli commented
> Is this intended to go out as a major change, sine `parseOpts` was changed to `resolveEslintConfig`?

Yes, I've started a milestone for a [`15.0.0` release](https://github.com/standard/standard-engine/milestone/1), thinking we do this + some of the other stuff mentioned in #234 + the #234 fix itself (I guess me, @Divlo or someone else can extract other stuff into standalone issues – like the "move to Promises", "move to ES6 class")

2021-08-16 13:58 UTC, voxpelli commented on README.md
>  ## API Usage
Totally agree! In some occasions I believe such blank lines are also significant in how Markdown parses things. Commited 👍

2021-08-16 14:18 UTC, Divlo commented
> (I guess me, @Divlo or someone else can extract other stuff into standalone issues – like the "move to Promises", "move to ES6 class")

Yep, we better separate this in multiple issues/PRs, as it is quite a big change. :smile:
New issues availables: #249, #250

> Yes, I've started a milestone for a 15.0.0 release

@voxpelli This release also includes #232 (already been merged).
Do you think, we do #234, #249, #250 and we release a new version or we can also include #231 in v15 ?
I mean we could make `standard@17` a big release.

2021-08-17 12:42 UTC, Divlo commented on test/api.js
>  test('api: parseOpts -- avoid self.eslintConfig parser mutation', function (t) {
Maybe we can rename this test, to use `resolveEslintConfig` instead of `parseOpts` reference.
(Same thing for line 51).

2021-08-17 12:48 UTC, Divlo commented
> Slight wish: That we merge this PR first :stuck_out_tongue:

Is there is anything missing to merge this PR and to make it "Ready for review" instead of "Draft"? @voxpelli 

> Actually test this with `standard` itself

Be aware that there is already a test for that and it is already passing (see: `test/clone.js`).

2021-08-18 10:20 UTC, voxpelli commented
> > Actually test this with `standard` itself
> 
> Be aware that there is already a test for that and it is already passing (see: `test/clone.js`).

Did not know! Let's merge then :)

2021-08-18 10:21 UTC, merged