Initial port to new api
standard/standard-engine pull request #275
Opened 2021-11-22 17:57 UTC by voxpelli

Fixes #234

Just throwing this out here, not thorougly tested, but all tests pass + all types are okay

2021-11-22 22:44 UTC, voxpelli commented
I could separate out the addition of `dependency-check`, `installed-check` and `npm-run-all` from this PR, but they added good assistance in helping to assure that I was on the right path.

2021-11-23 06:08 UTC, Divlo requested changes
Thanks for taking this task! @voxpelli 

Left some comments so we can discuss and improve the code.

Also: You forgot to update `README.md` about the changes.

2021-11-23 06:08 UTC, Divlo commented on test/api.js
> +  // @ts-ignore
Is this really necessary, is there is no way to avoid it?

In perfect world, we should not use `// eslint-disable-next-line` and `// @ts-ignore` comments.

2021-11-23 11:59 UTC, LinusU commented on bin/cmd.js
> +    if (result.some(result => result.errorCount || result.warningCount) === false) {
Or potentially: 

```suggestion
    if (result.every(result => result.errorCount === 0 || result.warningCount === 0)) {
```

Also, since `result` is typed as `LintResult[]` (as in "an array of LintResult") I think that we could name it `results` instead of `result`, which would avoid having the same name for the item and the array.

2021-11-23 12:03 UTC, voxpelli commented on bin/cmd.js
> +    if (result.some(result => result.errorCount || result.warningCount) === false) {
It was named `result.results` in the `CLIEngine` result, so this is a refactoring mistake by me, where I kept `result` rather than the intended `results`, so I agree with you on that one.

Will have to get back to the rest of the comments after work by the earliest. Thanks for quick responses 🙏

2021-11-29 13:46 UTC, voxpelli commented on index.js
> +// TODO: Remove
This was left in there because I needed to push the code in a hurry. Its intention was to be removed before merge.

2021-11-29 13:59 UTC, voxpelli commented on bin/cmd.js
> +    process.exitCode = result.some(result => result.errorCount) ? 1 : 0
> As you are checking for errors and warnings multiple times (here, isSomeWarning, hasErrorsOrWarning in my previous comment).

Most of this were already in the code, I'll refactor them out and smash them together.

2021-11-29 14:20 UTC, voxpelli commented on test/api.js
> +  // @ts-ignore
It was an attempt to avoid the typescript in this project to validate the typescript of the imported standard module, as that currently doesn't pass, as it uses new esmodule stuff which the `tsconfig.json` in this mproject does not allow.

It didn't fully work though, so I just deactivated type checking completely for test files unfortunately 🤷‍♂️

2021-11-29 15:01 UTC, voxpelli commented on package.json
> +    "test": "run-s check test:*"
I disagree that it makes things clearer +  that the `run-p` runs things in parallel, which is faster, especially locally.

This way adding / removing / changing a command becomes very clear.

2021-11-29 15:05 UTC, voxpelli commented on index.js
> +// FIXME: Rename to avoid confusion with ESLint provided "Linter"
This entire PR is a big **BREAKING CHANGE** 😉 Partly why I think this would be good to introduce here, the other part being that we now more directly reference eg. `LinterResult`, and its confusing to refer to a `LinterResult` when that refers to the ESLint [`Linter`](https://eslint.org/docs/7.0.0/developer-guide/nodejs-api#linter) rather than our own.

It was less confusing before when we referenced `CLIEngine` mostly.

Maybe name it `StandardEngine` instead?

2021-11-29 15:05 UTC, voxpelli commented on bin/cmd.js
> +    if (result.some(result => result.errorCount || result.warningCount) === false) {
I have now changed this 👍

2021-11-29 15:10 UTC, voxpelli commented
Tweaked and fixed things here, this should now be much more ready for merge 👍

2021-11-29 15:48 UTC, Divlo requested changes
Great job! 😊

Nearly ready for merging, there are still some comments to be addressed.

2021-11-29 15:48 UTC, Divlo commented on .github/workflows/lint.yml
> +  build:
Maybe we can rename this `linting` so we avoid the confusion with the other `build` job in the `nodejs.yml` file.
Also we could rename `nodejs.yml`.

Or, we can put the 2 different jobs in the `nodejs.yml` file.

I know that's not directly related with this PR, but as you created `lint.yml`, it's somehow related.

2021-11-29 15:48 UTC, Divlo commented on index.js
> +// FIXME: Rename to avoid confusion with ESLint provided "Linter"
I agree to rename from `Linter` to `StandardEngine` in this PR. :+1:
It makes sense.

2021-11-29 15:48 UTC, Divlo commented on package.json
> +    "test": "run-s check test:*"
Right. :+1+
We can keep `run-p`, I didn't know it runs in parallel.

The only thing, I think we don't need, is to have `test` and `test-ci`, it is not clear for me why we have both.

We can rename `test-ci` to `test` and remove `test`.
Locally, we can simply run `npm run check` and after `npm run test` or I don't mind to have a command to run both, but we can maybe name it differently than `test` as it runs not only `test` scripts but also `check` scripts.

2021-11-29 16:07 UTC, voxpelli commented on package.json
> +    "test": "run-s check test:*"
Best practice is that `npm test` should run all of the tests of a node project.

On CI though we want to run automated tests and linting separately, as linting only needs to be run once whereas automated tests should run on a combination of platforms.

Hence why there's both `test` and `test-ci`. Since they are only two different versions of sequential runs, `run-s`, there's not really any duplication there.

2021-11-29 16:16 UTC, voxpelli commented on .github/workflows/lint.yml
> +  build:
Done

2021-11-29 16:35 UTC, voxpelli commented
Updated `README` + `CHANGELOG` now as well

2021-11-30 06:13 UTC, Divlo commented on package.json
> +    "test": "run-s check test:*"
This suggested change is not really a big deal, it's non blocking for merging, so if you rather having `test` and `test-ci` it's fine like that for now but I would still rather not having `test-ci`.

> Best practice is that `npm test` should run all of the tests of a node project.

Yes, completely agree, but tests are not checks (linting, etc.).
We could separate these things.

> On CI though we want to run automated tests and linting separately, as linting only needs to be run once whereas automated tests should run on a combination of platforms.

True. :+1:

2021-11-30 06:22 UTC, Divlo approved these changes
LGTM! :rocket:

There are still some comments, but they are non blocking for merging.
As it is a big **BREAKING CHANGE** and a quite big PR, I would rather to have at least 2 reviews approval before merging.

The complicated thing will be to migrate all the engines to this new `standard-engine` and also the VSCode extension `vscode-standard`.

I'm wondering how can we offer a smooth upgrade as this new version (v15) of `standard-engine` introduce lot of BREAKING things.
We could maybe do prereleases for all engines, before making it stable.

2021-11-30 06:22 UTC, Divlo commented on CHANGELOG.md
> +- Change: make `--verbose` the default #232
We could argue, that this is also a **BREAKING CHANGE** as it removes an option from the CLI and it changes the default behavior.

2021-11-30 09:59 UTC, LinusU commented on CHANGELOG.md
> +- **BREAKING CHANGE:**  Print additional label on warnings (to separate them from errors) b7c1e17
```suggestion
- **BREAKING CHANGE:** Print additional label on warnings (to separate them from errors) b7c1e17
```

2021-11-30 10:03 UTC, LinusU approved these changes
Amazing! 🤩

2021-11-30 10:23 UTC, voxpelli commented on CHANGELOG.md
> +- Change: make `--verbose` the default #232
One could pretty much argue that bug fixes are breaking changes as well ;) Depends on what could be perceived as a public API to which one has guaranteed stability. In general I would say that CLI text output should not be treated as a public API unless explicitly stated to be for programmatic use

2021-11-30 10:27 UTC, merged

2021-11-30 10:28 UTC, voxpelli commented
@Divlo @LinusU Should we do a prerelease of 15.0.0 right away?

2021-11-30 12:29 UTC, Divlo commented
> @Divlo @LinusU Should we do a prerelease of 15.0.0 right away?

Yes, that would help. :+1: @voxpelli 
So we can already open PRs in the multiple engines (`standard`, `standardx`, `ts-standard`, `semistandard`) using this prerelease version, as there are probably multiple things that need to change.

2021-11-30 17:54 UTC, voxpelli commented
Prerelease done, update to `master` pending in #282